### ISSUE TITLE
Make sure there at at least five attributes for each model

### ISSUE THREAD

**Issue by daniel4657890** [daniel4657890/idb#28]

**Comment by ericchaoutaustin** [comment]
Player:
  name (first_name, last_name)
  number
  win/loss ratio, points per game, rebounds per game, assists per game
  team
  date of birth

Team:
  team_name
  coach
  mascot
  win/loss ratio, points per game
  home_venue

Game:
  id
  date
  duration
  home, away, winner
  venue

Venue:
  venue_name
  city
  capacity
  phone
  owner

I feel like unless Johnny can't find some of these attributes, this should be fine.
